/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'id' : string,
  'name' : string,
  'reps' : string,
  'sets' : bigint,
  'repType' : RepType,
  'notes' : [] | [string],
}
export interface MovementPattern {
  'id' : string,
  'name' : string,
  'exercises' : Array<Exercise>,
}
export type RepType = { 'timed' : null } |
  { 'amrap' : null } |
  { 'normal' : null };
export interface SelectedExercise {
  'exerciseId' : string,
  'patternId' : string,
}
export type Time = bigint;
export interface WorkoutDay {
  'id' : bigint,
  'patterns' : Array<MovementPattern>,
  'name' : string,
}
export interface WorkoutLog {
  'id' : string,
  'completedAt' : Time,
  'selectedExercises' : Array<SelectedExercise>,
  'dayId' : bigint,
}
export interface _SERVICE {
  'deleteWorkoutLog' : ActorMethod<[string], undefined>,
  'getProgram' : ActorMethod<[], Array<WorkoutDay>>,
  'getWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'logWorkout' : ActorMethod<[bigint, Array<[string, string]>], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];