/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RepType = IDL.Variant({
  'timed' : IDL.Null,
  'amrap' : IDL.Null,
  'normal' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'reps' : IDL.Text,
  'sets' : IDL.Nat,
  'repType' : RepType,
  'notes' : IDL.Opt(IDL.Text),
});
export const MovementPattern = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const WorkoutDay = IDL.Record({
  'id' : IDL.Nat,
  'patterns' : IDL.Vec(MovementPattern),
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const SelectedExercise = IDL.Record({
  'exerciseId' : IDL.Text,
  'patternId' : IDL.Text,
});
export const WorkoutLog = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : Time,
  'selectedExercises' : IDL.Vec(SelectedExercise),
  'dayId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteWorkoutLog' : IDL.Func([IDL.Text], [], []),
  'getProgram' : IDL.Func([], [IDL.Vec(WorkoutDay)], ['query']),
  'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'logWorkout' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RepType = IDL.Variant({
    'timed' : IDL.Null,
    'amrap' : IDL.Null,
    'normal' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'reps' : IDL.Text,
    'sets' : IDL.Nat,
    'repType' : RepType,
    'notes' : IDL.Opt(IDL.Text),
  });
  const MovementPattern = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const WorkoutDay = IDL.Record({
    'id' : IDL.Nat,
    'patterns' : IDL.Vec(MovementPattern),
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const SelectedExercise = IDL.Record({
    'exerciseId' : IDL.Text,
    'patternId' : IDL.Text,
  });
  const WorkoutLog = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : Time,
    'selectedExercises' : IDL.Vec(SelectedExercise),
    'dayId' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteWorkoutLog' : IDL.Func([IDL.Text], [], []),
    'getProgram' : IDL.Func([], [IDL.Vec(WorkoutDay)], ['query']),
    'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'logWorkout' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };